version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - database
    env_file:
      - .env
    entrypoint: './entrypoint.sh'
    volumes:
      - ".venv/"

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    
volumes:
  postgres_data:  # Define the volume for PostgreSQL data
