# Generated by Django 4.2.4 on 2023-08-13 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_score_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
